Table 2.7.2: Individual vulnerabilities identified among all young people starting treatment in 2016-17

In [1]:
from gssutils import *

if is_interactive():
    import requests
    from cachecontrol import CacheControl
    from cachecontrol.caches.file_cache import FileCache
    from cachecontrol.heuristics import LastModified
    from pathlib import Path

    session = CacheControl(requests.Session(),
                           cache=FileCache('.cache'),
                           heuristic=LastModified())

    sourceFolder = Path('in')
    sourceFolder.mkdir(exist_ok=True)

    inputURL = 'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/664944/'\
                    'Young-people-statistics-data-tables-from-the-national-drug-treatment-monitoring-system-2016-2017.xls'
    inputFile = sourceFolder / 'Young-people-statistics-data-tables-from-the-national-drug-treatment-monitoring-system-2016-2017.xls'
    response = session.get(inputURL)
    with open(inputFile, 'wb') as f:
      f.write(response.content)

In [2]:
tab = loadxlstabs(inputFile, sheetids='2.7.2 Vulnerabilities')[0]

Loading in\Young-people-statistics-data-tables-from-the-national-drug-treatment-monitoring-system-2016-2017.xls which has size 281600 bytes
Table names: ['2.7.2 Vulnerabilities']

In [3]:
observations = tab.excel_ref('B5').expand(DOWN).expand(RIGHT).is_not_blank()
observations

{<G15 0.07>, <F20 168.0>, <B19 92.0>, <C16 0.14>, <D8 1597.0>, <F6 6817.0>, <D12 1357.0>, <E7 0.39>, <B5 3386.0>, <F22 11753.0>, <E6 0.55>, <C9 0.28>, <E5 0.83>, <D7 3009.0>, <C12 0.13>, <G19 0.02>, <G16 0.06>, <E16 0.02>, <G18 0.02>, <B14 451.0>, <D5 6467.0>, <F7 3749.0>, <D20 106.0>, <B11 1225.0>, <G11 0.17>, <C6 0.64>, <D9 1411.0>, <B7 740.0>, <D11 719.0>, <E20 0.01>, <G17 0.04>, <C11 0.31>, <B20 62.0>, <G13 0.12>, <F15 857.0>, <D18 123.0>, <G21 0.01>, <G9 0.21>, <D16 123.0>, <F18 227.0>, <B6 2527.0>, <C18 0.03>, <C14 0.11>, <E22 1.0>, <F10 2108.0>, <E9 0.18>, <C22 1.0>, <E18 0.02>, <E14 0.06>, <C7 0.19>, <F16 688.0>, <F19 221.0>, <B17 230.0>, <B9 1093.0>, <E19 0.02>, <F5 9853.0>, <F17 414.0>, <F14 928.0>, <B13 542.0>, <E10 0.15>, <C10 0.24>, <G20 0.01>, <B16 565.0>, <D14 477.0>, <E8 0.2>, <D15 469.0>, <F11 1944.0>, <D6 4290.0>, <G12 0.16>, <F12 1869.0>, <C15 0.1>, <G5 0.84>, <F13 1400.0>, <B10 947.0>, <C5 0.86>, <C8 0.28>, <E11 0.09>, <E21 0.01>, <B21 43.0>, <F9 2504.0>, <D21 51.0>, <D13 858.0>, <G22 1.0>, <C21 0.01>, <G8 0.23>, <B15 388.0>, <D19 129.0>, <C17 0.06>, <E13 0.11>, <D17 184.0>, <B8 1110.0>, <C20 0.02>, <F8 2707.0>, <G14 0.08>, <B12 512.0>, <D10 1161.0>, <C19 0.02>, <E15 0.06>, <G7 0.32>, <E17 0.02>, <E12 0.17>, <G10 0.18>, <D22 7804.0>, <B18 104.0>, <C13 0.14>, <G6 0.58>, <B22 3949.0>, <F21 94.0>}

In [4]:
age = tab.excel_ref('A5').expand(DOWN).is_not_blank()
age

{<A11 'Self-harm'>, <A21 'Injecting'>, <A18 'Pregnant and/or parent'>, <A12 'NEET'>, <A5 'Early onset of substance misuse'>, <A6 'Poly substance user'>, <A10 'Mental health problem'>, <A22 'Total new presentations'>, <A16 'Sexual exploitation'>, <A14 'Child Protection Plan'>, <A13 'Looked after child'>, <A7 'Antisocial behaviour'>, <A9 'Affected by domestic abuse'>, <A19 'Opiate and/or crack use'>, <A15 'Child in need'>, <A17 'High risk alcohol user'>, <A20 'Housing problem'>, <A8 "Affected by others' substance misuse">}

In [5]:
sex = tab.excel_ref('B3').expand(RIGHT).is_not_blank() 
sex

{<F3 'Persons'>, <B3 'Female'>, <D3 'Male'>}

In [6]:
measuretype = tab.excel_ref('B4').expand(RIGHT).is_not_blank() 
measuretype

{<F4 'n'>, <E4 '%'>, <C4 '%'>, <B4 'n'>, <D4 'n'>, <G4 '%'>}

In [7]:
Dimensions = [
            HDim(age,'Basis of treatment',DIRECTLY,LEFT),
            HDim(sex,'Clients in treatment',CLOSEST,LEFT),
            HDim(measuretype,'Measure Type',DIRECTLY,ABOVE),
            HDimConst('Unit','People')            
            ]

In [8]:
c1 = ConversionSegment(observations, Dimensions, processTIMEUNIT=True)
# if is_interactive():
#     savepreviewhtml(c1)

In [9]:
new_table = c1.topandas()
new_table

,OBS,Basis of treatment,Clients in treatment,Measure Type,Unit
0,3386.00,Early onset of substance misuse,Female,n,People
1,0.86,Early onset of substance misuse,Female,%,People
2,6467.00,Early onset of substance misuse,Male,n,People
3,0.83,Early onset of substance misuse,Male,%,People
4,9853.00,Early onset of substance misuse,Persons,n,People
5,0.84,Early onset of substance misuse,Persons,%,People
6,2527.00,Poly substance user,Female,n,People
7,0.64,Poly substance user,Female,%,People
8,4290.00,Poly substance user,Male,n,People
9,0.55,Poly substance user,Male,%,People
10,6817.00,Poly substance user,Persons,n,People
11,0.58,Poly substance user,Persons,%,People
12,740.00,Antisocial behaviour,Female,n,People
13,0.19,Antisocial behaviour,Female,%,People
14,3009.00,Antisocial behaviour,Male,n,People
15,0.39,Antisocial behaviour,Male,%,People
16,3749.00,Antisocial behaviour,Persons,n,People
17,0.32,Antisocial behaviour,Persons,%,People
18,1110.00,Affected by others' substance misuse,Female,n,People
19,0.28,Affected by others' substance misuse,Female,%,People
20,1597.00,Affected by others' substance misuse,Male,n,People
21,0.20,Affected by others' substance misuse,Male,%,People
22,2707.00,Affected by others' substance misuse,Persons,n,People
23,0.23,Affected by others' substance misuse,Persons,%,People
24,1093.00,Affected by domestic abuse,Female,n,People
25,0.28,Affected by domestic abuse,Female,%,People
26,1411.00,Affected by domestic abuse,Male,n,People
27,0.18,Affected by domestic abuse,Male,%,People
28,2504.00,Affected by domestic abuse,Persons,n,People
29,0.21,Affected by domestic abuse,Persons,%,People
...,...,...,...,...,...
78,104.00,Pregnant and/or parent,Female,n,People
79,0.03,Pregnant and/or parent,Female,%,People
80,123.00,Pregnant and/or parent,Male,n,People
81,0.02,Pregnant and/or parent,Male,%,People
82,227.00,Pregnant and/or parent,Persons,n,People
83,0.02,Pregnant and/or parent,Persons,%,People
84,92.00,Opiate and/or crack use,Female,n,People
85,0.02,Opiate and/or crack use,Female,%,People
86,129.00,Opiate and/or crack use,Male,n,People
87,0.02,Opiate and/or crack use,Male,%,People
88,221.00,Opiate and/or crack use,Persons,n,People
89,0.02,Opiate and/or crack use,Persons,%,People
90,62.00,Housing problem,Female,n,People
91,0.02,Housing problem,Female,%,People
92,106.00,Housing problem,Male,n,People
93,0.01,Housing problem,Male,%,People
94,168.00,Housing problem,Persons,n,People
95,0.01,Housing problem,Persons,%,People
96,43.00,Injecting,Female,n,People
97,0.01,Injecting,Female,%,People
98,51.00,Injecting,Male,n,People
99,0.01,Injecting,Male,%,People
100,94.00,Injecting,Persons,n,People
101,0.01,Injecting,Persons,%,People
102,3949.00,Total new presentations,Female,n,People
103,1.00,Total new presentations,Female,%,People
104,7804.00,Total new presentations,Male,n,People
105,1.00,Total new presentations,Male,%,People
106,11753.00,Total new presentations,Persons,n,People
107,1.00,Total new presentations,Persons,%,People

In [10]:
new_table = new_table[new_table['OBS'] != 0 ]

In [11]:
new_table.columns = ['Value' if x=='OBS' else x for x in new_table.columns]

In [12]:
new_table['Basis of treatment'] = 'Vulnerability' +'/'+ new_table['Basis of treatment']

In [13]:
new_table.head()

,Value,Basis of treatment,Clients in treatment,Measure Type,Unit
0,3386.00,Vulnerability/Early onset of substance misuse,Female,n,People
1,0.86,Vulnerability/Early onset of substance misuse,Female,%,People
2,6467.00,Vulnerability/Early onset of substance misuse,Male,n,People
3,0.83,Vulnerability/Early onset of substance misuse,Male,%,People
4,9853.00,Vulnerability/Early onset of substance misuse,Persons,n,People

In [14]:
new_table['Basis of treatment'].unique()

array(['Vulnerability/Early onset of substance misuse',
       'Vulnerability/Poly substance user',
       'Vulnerability/Antisocial behaviour',
       "Vulnerability/Affected by others' substance misuse",
       'Vulnerability/Affected by domestic abuse',
       'Vulnerability/Mental health problem', 'Vulnerability/Self-harm',
       'Vulnerability/NEET', 'Vulnerability/Looked after child',
       'Vulnerability/Child Protection Plan',
       'Vulnerability/Child in need', 'Vulnerability/Sexual exploitation',
       'Vulnerability/High risk alcohol user',
       'Vulnerability/Pregnant and/or parent',
       'Vulnerability/Opiate and/or crack use',
       'Vulnerability/Housing problem', 'Vulnerability/Injecting',
       'Vulnerability/Total new presentations'], dtype=object)

In [15]:
new_table['Clients in treatment'] = new_table['Clients in treatment'].map(
    lambda x: {
        'Female' : 'F', 
        'Male' : 'M',
        'Persons' : 'T'
        }.get(x, x))

In [16]:
new_table.head()

,Value,Basis of treatment,Clients in treatment,Measure Type,Unit
0,3386.00,Vulnerability/Early onset of substance misuse,F,n,People
1,0.86,Vulnerability/Early onset of substance misuse,F,%,People
2,6467.00,Vulnerability/Early onset of substance misuse,M,n,People
3,0.83,Vulnerability/Early onset of substance misuse,M,%,People
4,9853.00,Vulnerability/Early onset of substance misuse,T,n,People

In [17]:
new_table['Measure Type'] = new_table['Measure Type'].map(
    lambda x: {
        'n' : 'Count', 
        '%' : 'Percentage',
        }.get(x, x))

In [18]:
new_table.tail()

,Value,Basis of treatment,Clients in treatment,Measure Type,Unit
103,1.0,Vulnerability/Total new presentations,F,Percentage,People
104,7804.0,Vulnerability/Total new presentations,M,Count,People
105,1.0,Vulnerability/Total new presentations,M,Percentage,People
106,11753.0,Vulnerability/Total new presentations,T,Count,People
107,1.0,Vulnerability/Total new presentations,T,Percentage,People

In [19]:
new_table.dtypes

Value                   float64
Basis of treatment       object
Clients in treatment     object
Measure Type             object
Unit                     object
dtype: object

In [20]:
new_table['Value'] = new_table['Value'].astype(str)

In [21]:
new_table.head(3)

,Value,Basis of treatment,Clients in treatment,Measure Type,Unit
0,3386.0,Vulnerability/Early onset of substance misuse,F,Count,People
1,0.86,Vulnerability/Early onset of substance misuse,F,Percentage,People
2,6467.0,Vulnerability/Early onset of substance misuse,M,Count,People

In [22]:
new_table['Period'] = '2016-17'
new_table['Substance'] = 'All'
new_table = new_table[['Period','Basis of treatment','Substance','Clients in treatment','Measure Type','Value','Unit']]

In [23]:
if is_interactive():
    SubstancetinationFolder = Path('out')
    SubstancetinationFolder.mkdir(exist_ok=True, parents=True)
    new_table.to_csv(SubstancetinationFolder / ('table2.7.2.csv'), index = False)

In [24]:
new_table.head()

,Period,Basis of treatment,Substance,Clients in treatment,Measure Type,Value,Unit
0,2016-17,Vulnerability/Early onset of substance misuse,All,F,Count,3386.0,People
1,2016-17,Vulnerability/Early onset of substance misuse,All,F,Percentage,0.86,People
2,2016-17,Vulnerability/Early onset of substance misuse,All,M,Count,6467.0,People
3,2016-17,Vulnerability/Early onset of substance misuse,All,M,Percentage,0.83,People
4,2016-17,Vulnerability/Early onset of substance misuse,All,T,Count,9853.0,People